VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "meanproj", primary: true do |meanproj|

    # add this to map your project folder into the vagrant image as custom packages folder
    #meanproj.vm.synced_folder "src/", "/home/vagrant/appserver/packages/custom"

    meanproj.vm.provider "docker" do |d|
      d.image = "gbevan/vagrant-meanio:0.6"
      d.has_ssh = true
      d.ports = ["3001:3000", "3444:3443"]
    end
  end
end
