VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "meanproj", primary: true do |meanproj|
    #meanproj.vm.provision "shell", inline: '/usr/bin/mongod --config /etc/mongod.conf --fork --smallfiles || /bin/true'
    meanproj.vm.synced_folder "src/", "/home/vagrant/appserver/packages/custom"
    meanproj.vm.provider "docker" do |d|
      d.image = "gbevan/vagrant-meanio:devel"
      d.has_ssh = true
      d.ports = ["3000:3000", "3443:3443"]
    end
  end
end
